onculture-build/OnCulture-Backend-V2

.github/PULL_REQUEST_TEMPLATE, .github/workflows/purge_artifacts.yaml
this workflow is to ensure that we purge unused artifacts every 6 hours
=> add purge artifacts workflow

nest-cli.json, src/auth/dto/allowed-user.dto.ts, src/auth/dto/change-password.dto.ts, src/auth/dto/company-info.dto.ts, src/auth/dto/login.dto.ts, src/auth/dto/reset-password.dto.ts, src/auth/dto/signup.dto.ts, src/auth/dto/user-info.dto.ts, src/common/database/pagination.dto.ts, src/common/interfaces/pagination-search-options.dto.ts, src/company/branch/dto/get-branches.dto.ts, src/company/branch/dto/update-branch.dto.ts, src/company/employee/dto/create-employee.dto.ts, src/company/employee/dto/get-employees.dto.ts, src/company/employee/job-level/dto/create-job-level.dto.ts, src/company/employee/job-role/dto/create-job-role.dto.ts
=> remove api property decorator from dtos

.eslintrc.js, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dto/create-allowed-users.dto.ts, src/auth/dto/find-allowed-user.dto.ts, src/auth/dto/login.dto.ts, src/auth/dto/request-password-reset.dto.ts, src/company/company.module.ts, src/company/department/department.controller.ts, src/company/department/department.maptype.ts, src/company/department/department.module.ts, src/company/department/department.service.ts, src/company/department/dto/create-department.dto.ts, src/company/department/dto/get-all-departments.dto.ts, src/company/department/dto/update-department-status.dto.ts, src/company/department/dto/update-department.dto.ts, src/company/employee/dto/create-employee.dto.ts, src/company/employee/dto/get-employees.dto.ts, src/company/employee/dto/update-employee.dto.ts, src/company/employee/employee.controller.ts, src/company/employee/employee.service.ts, src/company/employee/job-level/dto/create-job-level.dto.ts, src/company/employee/job-level/dto/update-job-level.dto.ts, src/company/employee/job-level/job-level.controller.ts, src/company/employee/job-level/job-level.service.ts, src/company/employee/job-role/job-role.service.ts
=> Auth, department and employee updates

src/auth/auth.service.ts, src/common/middleware/company.middleware.ts, src/main.ts
=> chore: refactor middleware

src/auth/auth.service.ts, src/auth/dto/find-allowed-user.dto.ts
=> chore: add unallowed users to waitlist

src/base/base-company/base-company.controller.ts, src/base/base-country/base-country.service.ts, src/base/base-state/base-state.service.ts, src/main.ts
=> chore: minor clean ups

src/common/database/database.module.ts, src/common/database/prisma-client-manager.ts, src/common/middleware/company.middleware.ts
=> chore: fix issue with database injection

src/main.ts
=> update origin for landing page

src/common/messaging/messaging.service.ts
=> fix: destructure message data

src/common/messaging/messaging.service.ts
=> chore: add exception if template does not exist

src/auth/auth.service.ts
=> chore: avoid setting password if the user has already set one

src/auth/auth.service.ts
=> fix: remove sign up email

src/base/base-company/base-company.service.ts
=> fix values creation

src/auth/auth.service.ts
=> fix: set-password check

src/auth/dto/request-password-reset.dto.ts
=> fix: reset password dto

src/base/base-company/base-company-request/base-company-request.service.ts
=> include check for existing company request

src/common/database/seed-data/company/employment-type.seed.ts, src/common/database/seed-data/runners/employment-type.runner.ts, src/common/prisma/company/migrations/20240925175955_create_employment_type_table/migration.sql, src/common/prisma/company/schema.prisma, src/common/prisma/seed-company.ts, src/company/company.service.ts, src/company/employee/dto/create-employee-type.dto.ts, src/company/employee/dto/create-employee.dto.ts, src/company/employee/dto/get-employees.dto.ts, src/company/employee/employee.controller.ts, src/company/employee/employee.service.ts, src/company/interfaces/index.ts
=> Employment types

src/company/employee/employee.service.ts
=> fix status filter when getting employees

src/auth/auth.service.ts, src/company/employee/employee.service.ts
=> fix: login logic and employee data

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dto/user-info.dto.ts, src/common/enums/index.ts, src/common/interfaces/index.ts, src/common/prisma/company/migrations/20240927114156_rename_suspended_to_deactivated/migration.sql, src/common/prisma/company/migrations/20240927183823_add_columns_to_the_user_model/migration.sql, src/common/prisma/company/migrations/20240927201402_add_email_and_phone_column_to_nok/migration.sql, src/common/prisma/company/migrations/20240927205305_add_unique_constraint_to_email_and_phone/migration.sql, src/common/prisma/company/migrations/20240927213804_add_marital_status_to_user/migration.sql, src/common/prisma/company/migrations/20240927223241_modify_address_model/migration.sql, src/common/prisma/company/schema.prisma, src/company/employee/dto/update-employee.dto.ts, src/company/employee/employee.controller.ts, src/company/employee/employee.service.ts, src/company/user/dto/emergency-contact.dto.ts, src/company/user/dto/employee-bank.dto.ts, src/company/user/dto/next-of-kin.dto.ts, src/company/user/dto/update-user.dto.ts, src/company/user/user.service.ts
- There are more checks carried out when trying to be authenticated to the system. this is to ensure that suspended users are unable to login to the system.
- Updating of employee information has also been done to cover the bio and contact information
=> Improve auth and implement employee update

src/company/employee/employee.controller.ts, src/company/user/user.service.ts
The PR just returns a message when an employee is created and it creates an employee without the role provided
=> chore: minor corrections to responses and method to create an employee without a role

src/company/integrations/integrations.service.ts
=> refactor: update redirect uri base client

src/company/employee/employee.service.ts
=> chore: add default role for employee

src/company/integrations/integrations.service.ts
=> fox route redirect

src/common/prisma/company/migrations/20241010165533_add_job_timeline_model/migration.sql, src/common/prisma/company/migrations/20241010182408_add_promotion_date_to_job_timeline/migration.sql, src/common/prisma/company/migrations/20241010191119_remove_level_id_from_job_role/migration.sql, src/common/prisma/company/migrations/20241010215712_add_join_and_exit_date_to_employee/migration.sql, src/common/prisma/company/schema.prisma, src/company/employee/dto/create-employee.dto.ts, src/company/employee/dto/update-employee.dto.ts, src/company/employee/employee.controller.ts, src/company/employee/employee.module.ts, src/company/employee/employee.service.ts, src/company/employee/job-role/dto/create-job-role.dto.ts, src/company/employee/job-role/job-role.service.ts, src/company/employee/job-timeline/dto/create-timeline.dto.ts, src/company/employee/job-timeline/dto/update-timeline.dto.ts, src/company/employee/job-timeline/job-timeline.controller.ts, src/company/employee/job-timeline/job-timeline.maptype.ts, src/company/employee/job-timeline/job-timeline.service.ts, src/company/user/user.service.ts
=> job timeline and modify employee methods

src/common/constants/index.ts, src/common/prisma/company/migrations/20241011104124_add_unique_constraint_to_joblevel_rank/migration.sql, src/common/prisma/company/schema.prisma, src/company/employee/csv/dto/field-type.dto.ts, src/company/employee/job-level/job-level.service.ts
=> chore: job level

src/app.module.ts, src/auth/auth.controller.ts, src/auth/guard/app.guard.ts, src/auth/guard/composite.guard.ts, src/auth/guard/subdomain.guard.ts, src/base/base-company/base-company-request/base-company-request.service.ts, src/base/base-company/base-company.controller.ts, src/common/database/prisma-client-manager.ts, src/common/decorators/route.decorator.ts, src/company/company.module.ts
=> chore: add sudomain guard to the system

src/auth/dto/user-info.dto.ts, src/auth/guard/subdomain.guard.ts, src/company/employee/employee.service.ts, src/company/queue/consumer.ts, src/company/user/user.service.ts, tsconfig.json
=> fix issue around bulk upload failing due to restrictions 

src/common/prisma/company/migrations/20241015081845_add_course_subscription_models/migration.sql, src/common/prisma/company/schema.prisma, src/common/prisma/migrations/20241015081807_add_course_models/migration.sql, src/common/prisma/schema.prisma
I have not added migration files yet. review the schemas and then i would add the migration files
=> Add models for courses

src/common/database/seed-data/base/sanity-courses.seed.ts, src/common/third-party/providers/sanity/sanity.service.ts, src/common/utils/app.utilities.ts, src/company/course/course.controller.ts, src/company/course/course.module.ts, src/company/course/course.service.ts, src/company/course/employee/employee-course.maptype.ts, src/company/course/employee/employee-course.service.ts, src/company/employee/employee.controller.ts, src/main.ts
=> Update sanity seed files and add methods for employee course

src/base/base-course/base-course.controller.ts, src/company/course/course.controller.ts
=> chore: add auth strategy to courses

src/company/course/course.service.ts, src/company/queue/consumer.ts, src/company/queue/producer.ts
=> added logs to trace issues

src/company/course/course.service.ts, src/company/queue/producer.ts
=> add traces
